@startuml

participant localStorage
participant URLParams
participant App
participant FirebaseAuth
participant Firestore

==メンテナンス確認==

App -> Firestore: メンテナンス状態確認（認証不要）

opt メンテナンス中の場合
App -> App: メンテナンス画面表示
note right: 以降の処理は行わない
end

==認証状態確認==

App -> FirebaseAuth: 認証状態確認

alt 認証済み
    App <-- FirebaseAuth: 認証トークン(uid)取得
else 未認証
    App <-- FirebaseAuth: null返却
    App -> FirebaseAuth: signInAnonymously()コール
    App <-- FirebaseAuth: 認証トークン(uid)取得
end

==遷移先判定==

App -> localStorage: localStorageからroomId取得試行
App -> URLParams: URLパラメータからroomId取得試行

alt localStorageにroomIdが存在する場合
    App -> Firestore: 部屋情報取得リクエスト(roomId)
        
    alt 部屋に復帰可能な場合
        note across: 以下を全て満たす場合に復帰可能\n・部屋の状態がaccepting/full/inProgress\n・ユーザーのUIDが該当する部屋のplayersに含まれている
        App -> App: <color:red>部屋復帰確認ダイアログを表示</color>
        
        alt <color:red>部屋に戻ることを選択した場合</color>
            alt 部屋の状態が accepting または full の場合
                App -> App: ゲーム選択画面を表示
            else 部屋の状態が inProgress の場合
                App -> App: currentGameに従い、ゲーム中画面を表示
            end
        else <color:red>TOP画面に戻ることを選択した場合</color>
            App -> localStorage: <color:red>roomId削除</color>
            note right #ffcccc: user_propertyのroomIdも削除
            
            opt <color:red>URLパラメータのroomIdがlocalStorageと一致する場合</color>
                App -> URLParams: <color:red>URLパラメータからroomId削除</color>
            end

            App -> App: <color:red>TOP画面を表示</color>
            note right: ・エラーメッセージは表示しない\n・URLパラメータにroomIdが存在する場合は、\n「部屋参加」押下時に部屋コードが自動入力されていること\n（ただし部屋コードは編集可能であること）
            note across: 誤ってTOPに戻ることを選んでしまった場合、元いた部屋のゲームがそれ以上進行できなくなる
        end
    else 部屋に復帰不可能な場合
        note across: 例）部屋の状態がclose、または既に削除されている場合
        App -> localStorage: <color:red>roomId削除</color>
        note right #ffcccc: user_propertyのroomIdも削除
                
        opt <color:red>URLパラメータのroomIdがlocalStorageと一致する場合</color>
            App -> URLParams: <color:red>URLパラメータからroomId削除</color>
        end

        App -> App: <color:red>TOP画面を表示</color>
        note right: ・エラーメッセージは表示しない\n・URLパラメータにroomIdが存在する場合は、\n「部屋参加」押下時に部屋コードが自動入力されていること\n（ただし部屋コードは編集可能であること）
    end

else localStorageにroomIdが存在しない場合

    alt URLパラメータのroomIdが存在する場合
        App -> Firestore: 部屋情報取得リクエスト(URLのroomId)

        alt 部屋の状態がacceptingの場合
            App <-- Firestore: 部屋情報(accepting)
            App -> App: ユーザー情報登録ダイアログ表示
            note right: 部屋コードが自動入力されていること\n（ただし部屋コードは編集可能であること）
        else 部屋の状態がaccepting以外の場合（削除済みも含む）
            App <-- Firestore: 部屋情報(accepting以外) または エラーレスポンス
            App -> URLParams: URLパラメータからroomId削除
            App -> App: TOP画面を表示
            note right: ・エラーメッセージは表示しない\n・部屋参加時に部屋コード入力可            
        end
    else URLパラメータのroomIdが存在しない場合
        App -> App: TOP画面表示
    end

end

@enduml
