@startuml

entity rooms as "rooms\n部屋" {
    + id [PK]
    --
    players_count [プレイヤー人数]
    status [ステータス]
    current_turn_count [現在のターン数]
    created_at [作成日]
    updated_at [更新日]
}

entity players as "players\nプレイヤー" {
    + id [PK]
    --
    # room_id [FK]
    nickname [ニックネーム]
    role [役割]
    ever_been_parent [既に親を担ったか]
    points [ポイント]
    created_at [作成日]
    updated_at [更新日]
}

entity character_cards as "character_cards\n人物カード" {
    + id [PK]
    --
    image_path [画像パス]
    created_at [作成日]
    updated_at [更新日]
}

entity profile_cards as "profile_cards\nプロフィールカード" {
    + id [PK]
    --
    content [内容]
    created_at [作成日]
    updated_at [更新日]
}

entity character_card_usage_history as "character_card_usage_history\n人物カード使用履歴" {
    + id [PK]
    --
    # room_id [FK]
    # character_card_id [FK]
    is_correct [正解か否か]
    turn_count [ターン数]
    created_at [作成日]
    updated_at [更新日]
}

entity profile_card_usage_history as "profile_card_usage_history\nプロフィールカード使用履歴" {
    + id [PK]
    --
    # room_id [FK]
    # profile_card_id [FK]
    # player_id [FK]
    input_profile [入力されたプロファイル情報]
    turn_count [ターン数]
    created_at [作成日]
    updated_at [更新日]
}

rooms ||..|{ players
rooms ||..|{ character_card_usage_history
rooms ||..|{ profile_card_usage_history
character_cards ||..|{ character_card_usage_history
profile_cards ||..|{ profile_card_usage_history
players ||..|{ profile_card_usage_history

@enduml
