name: Deploy to Staging

on:
  push:
    branches:
      - 'release/*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Make build script executable
        run: chmod +x ./frontend/build_scripts/build_web.sh

      - name: Build for Staging
        run: ./frontend/build_scripts/build_web.sh stg

      - name: Deploy to Firebase Hosting (Staging)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BDGHUB_STG }}'
          projectId: bdghub-stg
          channelId: live
